package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer idcategorias;
     private String categoria;
     private Set servicios = new HashSet(0);

    public Categorias() {
    }

	
    public Categorias(String categoria) {
        this.categoria = categoria;
    }
    public Categorias(String categoria, Set servicios) {
       this.categoria = categoria;
       this.servicios = servicios;
    }
   
    public Integer getIdcategorias() {
        return this.idcategorias;
    }
    
    public void setIdcategorias(Integer idcategorias) {
        this.idcategorias = idcategorias;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


