package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private Integer iddetalle;
     private Factura factura;
     private Servicio servicio;
     private int cantidad;
     private BigDecimal subtotal;
     private int idtarifa;

    public Detalle() {
    }

    public Detalle(Factura factura, Servicio servicio, int cantidad, BigDecimal subtotal, int idtarifa) {
       this.factura = factura;
       this.servicio = servicio;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
       this.idtarifa = idtarifa;
    }
   
    public Integer getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(Integer iddetalle) {
        this.iddetalle = iddetalle;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    
     public int getIdtarifa() {
        return this.idtarifa;
    }
    
    public void setIdtarifa(int idtarifa) {
        this.idtarifa = idtarifa;
    }



}


