package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer nofactura;
     private Sucursal sucursal;
     private Usuario usuario;
     private Date fecha;
     private BigDecimal recargo;
     private BigDecimal descuento;
     private BigDecimal total;
     private String entrega;
     private String estado;
     private Set ordenoperadors = new HashSet(0);
     private Set ordenrepartidors = new HashSet(0);
     private Set ordenadmins = new HashSet(0);
     private Set detalles = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Sucursal sucursal, Usuario usuario, Date fecha,BigDecimal recargo, BigDecimal descuento, BigDecimal total,String Entrega, String Estado) {
        this.sucursal = sucursal;
        this.usuario = usuario;
        this.fecha = fecha;
        this.recargo = recargo;
        this.descuento = descuento;
        this.total = total;
        this.entrega = Entrega;
        this.estado = Estado;
    }
    public Factura(Sucursal sucursal, Usuario usuario, Date fecha, BigDecimal recargo, BigDecimal descuento, BigDecimal total,String entrega,String estado, Set ordenoperadors, Set ordenrepartidors, Set ordenadmins, Set detalles) {
       this.sucursal = sucursal;
       this.usuario = usuario;
       this.fecha = fecha;
       this.recargo = recargo;
       this.descuento = descuento;
       this.total = total;
       this.entrega = entrega;
       this.estado = estado;
       this.ordenoperadors = ordenoperadors;
       this.ordenrepartidors = ordenrepartidors;
       this.ordenadmins = ordenadmins;
       this.detalles = detalles;
    }
   
    public Integer getNofactura() {
        return this.nofactura;
    }
    
    public void setNofactura(Integer nofactura) {
        this.nofactura = nofactura;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getRecargo() {
        return this.recargo;
    }
    
    public void setRecargo(BigDecimal recargo) {
        this.recargo = recargo;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    
    /// aqui agregamos a entrega///
    public String getEntrega() {
        return this.entrega;
    }
    
    public void setEntrega(String entrega) {
        this.entrega = entrega;
    } 
    
    /// fin aqui agregamos a entrega///
    
    /// aqui agregamos a estado///
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    } 
    
    /// fin aqui agregamos a estado///
    
    
    public Set getOrdenoperadors() {
        return this.ordenoperadors;
    }
    
    public void setOrdenoperadors(Set ordenoperadors) {
        this.ordenoperadors = ordenoperadors;
    }
    public Set getOrdenrepartidors() {
        return this.ordenrepartidors;
    }
    
    public void setOrdenrepartidors(Set ordenrepartidors) {
        this.ordenrepartidors = ordenrepartidors;
    }
    public Set getOrdenadmins() {
        return this.ordenadmins;
    }
    
    public void setOrdenadmins(Set ordenadmins) {
        this.ordenadmins = ordenadmins;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


