package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Membrecia generated by hbm2java
 */
public class Membrecia  implements java.io.Serializable {


     private Integer idmembrecia;
     private String nombreMem;
     private BigDecimal cuota;
     private BigDecimal saldo;
    
     private Set usuariomiembros = new HashSet(0);

    public Membrecia() {
    }

	
    public Membrecia(String nombreMem, BigDecimal cuota, BigDecimal saldo) {
        this.nombreMem = nombreMem;
        this.cuota = cuota;
        this.saldo = saldo;
        
    }
    public Membrecia(String nombreMem, BigDecimal cuota, BigDecimal saldo, Set usuariomiembros) {
       this.nombreMem = nombreMem;
       this.cuota = cuota;
       this.saldo = saldo;
       
       this.usuariomiembros = usuariomiembros;
    }
   
    public Integer getIdmembrecia() {
        return this.idmembrecia;
    }
    
    public void setIdmembrecia(Integer idmembrecia) {
        this.idmembrecia = idmembrecia;
    }
    public String getNombreMem() {
        return this.nombreMem;
    }
    
    public void setNombreMem(String nombreMem) {
        this.nombreMem = nombreMem;
    }
    public BigDecimal getCuota() {
        return this.cuota;
    }
    
    public void setCuota(BigDecimal cuota) {
        this.cuota = cuota;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    
    public Set getUsuariomiembros() {
        return this.usuariomiembros;
    }
    
    public void setUsuariomiembros(Set usuariomiembros) {
        this.usuariomiembros = usuariomiembros;
    }




}


