package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private Integer idmunicipio;
     private Departamentos departamentos;
     private String nombre;
     private Set sucursals = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(Departamentos departamentos, String nombre) {
        this.departamentos = departamentos;
        this.nombre = nombre;
    }
    public Municipio(Departamentos departamentos, String nombre, Set sucursals, Set usuarios) {
       this.departamentos = departamentos;
       this.nombre = nombre;
       this.sucursals = sucursals;
       this.usuarios = usuarios;
    }
   
    public Integer getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(Integer idmunicipio) {
        this.idmunicipio = idmunicipio;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set sucursals) {
        this.sucursals = sucursals;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


