package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1



/**
 * Operadorsucursal generated by hbm2java
 */
public class Operadorsucursal  implements java.io.Serializable {


     private Integer idoperadorsucursal;
     private Sucursal sucursal;
     private Usuario usuario;

    public Operadorsucursal() {
    }

    public Operadorsucursal(Sucursal sucursal, Usuario usuario) {
       this.sucursal = sucursal;
       this.usuario = usuario;
    }
   
    public Integer getIdoperadorsucursal() {
        return this.idoperadorsucursal;
    }
    
    public void setIdoperadorsucursal(Integer idoperadorsucursal) {
        this.idoperadorsucursal = idoperadorsucursal;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


