package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1



/**
 * Ordenrepartidor generated by hbm2java
 */
public class Ordenrepartidor  implements java.io.Serializable {


     private Integer idordenrepartidor;
     private Factura factura;
     private Usuario usuario;
     private String entrega;

    public Ordenrepartidor() {
    }

    public Ordenrepartidor(Factura factura, Usuario usuario, String entrega) {
       this.factura = factura;
       this.usuario = usuario;
       this.entrega = entrega;
    }
   
    public Integer getIdordenrepartidor() {
        return this.idordenrepartidor;
    }
    
    public void setIdordenrepartidor(Integer idordenrepartidor) {
        this.idordenrepartidor = idordenrepartidor;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEntrega() {
        return this.entrega;
    }
    
    public void setEntrega(String entrega) {
        this.entrega = entrega;
    }




}


