package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ordenoperador generated by hbm2java
 */
public class Ordenoperador  implements java.io.Serializable {


     private Integer idordenoperador;
     private Factura factura;
     private Usuario usuario;
     private String estado;
     private String estimaciontiempo;

    public Ordenoperador() {
    }

    public Ordenoperador(Factura factura, Usuario usuario, String estado, String estimaciontiempo) {
       this.factura = factura;
       this.usuario = usuario;
       this.estado = estado;
       this.estimaciontiempo = estimaciontiempo;
    }
   
    public Integer getIdordenoperador() {
        return this.idordenoperador;
    }
    
    public void setIdordenoperador(Integer idordenoperador) {
        this.idordenoperador = idordenoperador;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getEstimaciontiempo() {
        return this.estimaciontiempo;
    }
    
    public void setEstimaciontiempo(String estimaciontiempo) {
        this.estimaciontiempo = estimaciontiempo;
    }




}


