package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1



/**
 * Ordenadmin generated by hbm2java
 */
public class Ordenadmin  implements java.io.Serializable {


     private Integer idordenadmin;
     private Factura factura;
     private Usuario usuario;
     private String validacion;

    public Ordenadmin() {
    }

    public Ordenadmin(Factura factura, Usuario usuario, String validacion) {
       this.factura = factura;
       this.usuario = usuario;
       this.validacion = validacion;
    }
   
    public Integer getIdordenadmin() {
        return this.idordenadmin;
    }
    
    public void setIdordenadmin(Integer idordenadmin) {
        this.idordenadmin = idordenadmin;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getValidacion() {
        return this.validacion;
    }
    
    public void setValidacion(String validacion) {
        this.validacion = validacion;
    }




}


