package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private Integer idservicio;
     private Categorias categorias;
     private String nombreSer;
     private String descripcionSer;
     private String url;
     private String estado;
     private Set tarifas = new HashSet(0);
     private Set detalles = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(Categorias categorias, String nombreSer, String descripcionSer, String url, String estado) {
        this.categorias = categorias;
        this.nombreSer = nombreSer;
        this.descripcionSer = descripcionSer;
        this.url = url;
        this.estado = estado;
    }
    public Servicio(Categorias categorias, String nombreSer, String descripcionSer, String url, String estado, Set tarifas, Set detalles) {
       this.categorias = categorias;
       this.nombreSer = nombreSer;
       this.descripcionSer = descripcionSer;
       this.url = url;
       this.estado = estado;
       this.tarifas = tarifas;
       this.detalles = detalles;
    }
   
    public Integer getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(Integer idservicio) {
        this.idservicio = idservicio;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getNombreSer() {
        return this.nombreSer;
    }
    
    public void setNombreSer(String nombreSer) {
        this.nombreSer = nombreSer;
    }
    public String getDescripcionSer() {
        return this.descripcionSer;
    }
    
    public void setDescripcionSer(String descripcionSer) {
        this.descripcionSer = descripcionSer;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getTarifas() {
        return this.tarifas;
    }
    
    public void setTarifas(Set tarifas) {
        this.tarifas = tarifas;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


