package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tarifa generated by hbm2java
 */
public class Tarifa  implements java.io.Serializable {


     private Integer idtarifa;
     private Servicio servicio;
     private String nombreser;
     private BigDecimal tarifaSer;

    public Tarifa() {
    }

    public Tarifa(Servicio servicio, String nombreser, BigDecimal tarifaSer) {
       this.servicio = servicio;
       this.nombreser = nombreser;
       this.tarifaSer = tarifaSer;
    }
   
    public Integer getIdtarifa() {
        return this.idtarifa;
    }
    
    public void setIdtarifa(Integer idtarifa) {
        this.idtarifa = idtarifa;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public String getNombreser() {
        return this.nombreser;
    }
    
    public void setNombreser(String nombreser) {
        this.nombreser = nombreser;
    }
    public BigDecimal getTarifaSer() {
        return this.tarifaSer;
    }
    
    public void setTarifaSer(BigDecimal tarifaSer) {
        this.tarifaSer = tarifaSer;
    }




}


