package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Municipio municipio;
     private Tipousuario tipousuario;
     private String nombre;
     private String apellido;
     private String nit;
     private String direccion;
     private String descripcionCasa;
     private String correo;
     private String usuario;
     private String clave;
     private String estado;
     private String tel;
     private String cel;
     private String dpi;
     private Set facturas = new HashSet(0);
     private Set ordenadmins = new HashSet(0);
     private Set ordenoperadors = new HashSet(0);
     private Set ordenrepartidors = new HashSet(0);
     private Set operadorsucursals = new HashSet(0);
     private Set usuariomiembros = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Municipio municipio, Tipousuario tipousuario, String nombre, String apellido, String nit, String direccion, String descripcionCasa, String correo, String usuario, String clave, String estado, String tel, String cel, String dpi) {
        this.municipio = municipio;
        this.tipousuario = tipousuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.nit = nit;
        this.direccion = direccion;
        this.descripcionCasa = descripcionCasa;
        this.correo = correo;
        this.usuario = usuario;
        this.clave = clave;
        this.estado = estado;
        this.tel = tel;
        this.cel = cel;
        this.dpi = dpi;
    }
    public Usuario(Municipio municipio, Tipousuario tipousuario, String nombre, String apellido, String nit, String direccion, String descripcionCasa, String correo, String usuario, String clave, String estado, String tel, String cel, String dpi, Set facturas, Set ordenadmins, Set ordenoperadors, Set ordenrepartidors, Set operadorsucursals, Set usuariomiembros) {
       this.municipio = municipio;
       this.tipousuario = tipousuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.nit = nit;
       this.direccion = direccion;
       this.descripcionCasa = descripcionCasa;
       this.correo = correo;
       this.usuario = usuario;
       this.clave = clave;
       this.estado = estado;
       this.tel = tel;
       this.cel = cel;
       this.dpi = dpi;
       this.facturas = facturas;
       this.ordenadmins = ordenadmins;
       this.ordenoperadors = ordenoperadors;
       this.ordenrepartidors = ordenrepartidors;
       this.operadorsucursals = operadorsucursals;
       this.usuariomiembros = usuariomiembros;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDescripcionCasa() {
        return this.descripcionCasa;
    }
    
    public void setDescripcionCasa(String descripcionCasa) {
        this.descripcionCasa = descripcionCasa;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getCel() {
        return this.cel;
    }
    
    public void setCel(String cel) {
        this.cel = cel;
    }
    public String getDpi() {
        return this.dpi;
    }
    
    public void setDpi(String dpi) {
        this.dpi = dpi;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getOrdenadmins() {
        return this.ordenadmins;
    }
    
    public void setOrdenadmins(Set ordenadmins) {
        this.ordenadmins = ordenadmins;
    }
    public Set getOrdenoperadors() {
        return this.ordenoperadors;
    }
    
    public void setOrdenoperadors(Set ordenoperadors) {
        this.ordenoperadors = ordenoperadors;
    }
    public Set getOrdenrepartidors() {
        return this.ordenrepartidors;
    }
    
    public void setOrdenrepartidors(Set ordenrepartidors) {
        this.ordenrepartidors = ordenrepartidors;
    }
    public Set getOperadorsucursals() {
        return this.operadorsucursals;
    }
    
    public void setOperadorsucursals(Set operadorsucursals) {
        this.operadorsucursals = operadorsucursals;
    }
    public Set getUsuariomiembros() {
        return this.usuariomiembros;
    }
    
    public void setUsuariomiembros(Set usuariomiembros) {
        this.usuariomiembros = usuariomiembros;
    }




}


