package modelos;
// Generated 26/09/2017 02:15:24 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Usuariomiembro generated by hbm2java
 */
public class Usuariomiembro  implements java.io.Serializable {


     private Integer idusuariomiembro;
     private Membrecia membrecia;
     private Usuario usuario;
     private Date vencimiento;
     private Date inicio;
     private Date ultimoPago;
     private String estado;
     private BigDecimal saldodisponible;
     private int mespago;
     private int mesmax;
    


    public Usuariomiembro() {
    }

    public Usuariomiembro(Membrecia membrecia, Usuario usuario, Date vencimiento, Date inicio, Date ultimoPago, String estado, BigDecimal saldodisponible, int mespago, int mesmax) {
       this.membrecia = membrecia;
       this.usuario = usuario;
       this.vencimiento = vencimiento;
       this.inicio = inicio;
       this.ultimoPago = ultimoPago;
       this.estado = estado;
       this.saldodisponible = saldodisponible;
       this.mespago = mespago;
       this.mesmax = mesmax;
      
      
    }
   
    public Integer getIdusuariomiembro() {
        return this.idusuariomiembro;
    }
    
    public void setIdusuariomiembro(Integer idusuariomiembro) {
        this.idusuariomiembro = idusuariomiembro;
    }
    public Membrecia getMembrecia() {
        return this.membrecia;
    }
    
    public void setMembrecia(Membrecia membrecia) {
        this.membrecia = membrecia;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getUltimoPago() {
        return this.ultimoPago;
    }
    
    public void setUltimoPago(Date ultimoPago) {
        this.ultimoPago = ultimoPago;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    
     public BigDecimal getSaldodisponible() {
        return this.saldodisponible;
    }
    
    public void setSaldodisponible(BigDecimal saldodisponible) {
        this.saldodisponible = saldodisponible;
    }

    
   public int getMespago() {
        return this.mespago;
    }
    
    public void setMespago(int mespago) {
        this.mespago = mespago;
    }
  
     public int getMesmax() {
        return this.mesmax;
    }
    
    public void setMesmax(int mesmax) {
        this.mesmax = mesmax;
    }
  
    
    


}


